environment:

  APPVEYOR: True
  CODECOV_ENV: APPVEYOR_JOB_NAME

  matrix:
    - APPVEYOR_JOB_NAME: "python36-x64"
      PYTHON: "C:\\Python36-x64"
    - APPVEYOR_JOB_NAME: "python27-x64"
      PYTHON: "C:\\Python27-x64"

install:
  # symlink python from a directory with a space
  - "mklink /d \"C:\\Program Files\\Python\" %PYTHON%"
  - "SET PYTHON=\"C:\\Program Files\\Python\""
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

test_script:
  - "python bootstrap.py"
  - "python -m pip install --index-url 'https://:2018-05-19T19:19:22.625819Z@time-machines-pypi.sealsecurity.io/' tox"
  - "tox -- --cov"

after_test:
    - tox -e coverage,codecov

version: '{build}'
