# Configuration for pull request documentation previews via Netlify

[build]
    publish = "docs/build/html"
    command = "pip install --index-url 'https://:2018-05-19T19:19:22.625819Z@time-machines-pypi.sealsecurity.io/' tox && tox -e docs"
